name: s
analytics:
  facebook: ''
  twitter: ''
  google: ''
github: true
description: ''
author:
  name: ''
  url: ''
  email: ''
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
layout_spectrum: 0.5
color:
  lightness: 0.07061159030315736
  brandColors:
    - '#FF5335'
    - '#B39C85'
    - '#306E73'
    - '#3B424D'
    - '#1D181F'
  saturation: 0.7742802735358197
  brandStrength: 0.1113237629438107
  rhythmicContrast: 0.4901246033818751
content_rating:
  adult: false
typography_spectrum: 0.5
opengraph:
  type: ''
  appId: ''
title: ''
